metanorma/homebrew-metanorma

- .travis.yml
- Formula/metanorma.rb
> Add dependency section

- .travis.yml
- Formula/metanorma.rb
- https://github.com/riboseinc/homebrew-metanorma/issues/4
> Add libffi as dependency

- Formula/metanorma.rb
> Update metanorma-cli gem to v1.1.3

- Formula/metanorma.rb
- README.adoc
- https://github.com/metanorma/homebrew-metanorma/issues/10
> Migration to metanorma group

- .gitignore
- .travis.yml
- Formula/metanorma.rb
- README.adoc
- https://github.com/metanorma/metanorma-ogc/issues/21#issuecomment-468264446
- https://github.com/metanorma/metanorma-ogc/issues/21#issuecomment-469086448
> Enable latexml test

- .travis.yml
- Formula/metanorma.rb
> Release 1.1.7

- .travis.yml
> Add formula upgrade test

- Formula/metanorma.rb
- https://github.com/metanorma/metanorma-linux-setup/issues/10
> Add idnits-2.16.02 resource

- Formula/metanorma.rb
> #25 add yq dependency

- .travis.yml
- Formula/metanorma.rb
- https://github.com/metanorma/homebrew-metanorma/pull/27#issuecomment-513317248
> Remove nokogiri explicit installation

- .github/workflows/linux.yml
- .github/workflows/macos.yml
- Formula/metanorma.rb
> #34 fix broken CI

- .github/workflows/release.yml
- Formula/metanorma.rb
- formula-set-version.sh
> #32 listen for metanorma-cli release

- Formula/metanorma.rb
> #43 add openjdk dependency

- Formula/metanorma.rb
- #36 
!!! Should be merged after https://github.com/metanorma/metanorma-cli/pull/139 release
> #36 add caveats to run 'metanorma setup'

- .github/workflows/macos.yml
> #72 add macos-11 to test matrix

- Formula/metanorma-dev.rb
- Formula/metanorma.rb
- https://github.com/metanorma/metanorma-cli/pull/252
> Add graphviz to required dependency

- .github/workflows/linux.yml
- Formula/metanorma.rb
> #70 fix checkout for linux workflow

- .github/workflows/linux.yml
- .github/workflows/macos.yml
- Formula/xml2rfc.rb
> #79 add xml2rfc formula

- .github/workflows/linux.yml
- .github/workflows/macos.yml
> #82 ignore potential link issues on brew install

- .github/workflows/linux.yml
- .github/workflows/macos.yml
- Formula/metanorma.rb
- Formula/xml2rfc.rb
- formula-set-version.sh
> Update brew formulae to match packed-mn artifacts 

- .github/workflows/macos.yml
> feat: update macos.yml for macOS 13, 14, 15, retire 12, fixes #91

- .github/workflows/linux.yml
> GHA Linux: add os to the matrix

- Formula/metanorma-dev.rb
- Formula/metanorma.rb
> fix: formula
